baseURL: ""
languageCode: en-us
title: Amr Shawky
theme: PaperMod

params:

  homeInfoParams:
    Title: "Hello World!"
    Content: "Welcome to my Blog I'm Amr, etc.,"
  socialIcons:
    - name: instagram
      url: 'https://www.instagram.com/amr.as90'

  cover:
    linkFullImages: true



  
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true


menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10

    - identifier: search
      name: 🔍
      url: /search/
      weight: 50

    - identifer: archives
      name: Archives
      url: /archives/
      weight: 20

    - identifer: about
      name: About
      url: /about/
      weight: 30


outputs:
    home:
        - HTML
        - RSS
        - JSON
